version: '3'
services:
  db:
    image: postgres
  redis:
    image: redis
  app:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/dashous
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/12"
