default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres

development:
  <<: *default
  database: dashous_development

test:
  <<: *default
  database: dashous_test

production:
  <<: *default
  database: dashous_production
  username: dashous
  password: <%= ENV['DASHOUS_DATABASE_PASSWORD'] %>
